// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoginDemo.Models.EFModels;

public partial class Orgs
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? OrgNo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}