// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoginDemo.Models.EFModels;

public partial class Syslog
{
    public int SeqNo { get; set; }

    public string Acount { get; set; }

    public string Ipaddress { get; set; }

    public DateTime LoginAt { get; set; }

    public DateTime CreatedAt { get; set; }
}