// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoginDemo.Models.EFModels;

public partial class Users
{
    public int Id { get; set; }

    public int OrgId { get; set; }

    public string Name { get; set; }

    public DateTime? Birthday { get; set; }

    public string Email { get; set; }

    public string Acount { get; set; }

    public string Password { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ApplyFile> ApplyFile { get; set; } = new List<ApplyFile>();

    public virtual Orgs Org { get; set; }
}